### ISSUE TITLE
Make it easier to change Backpack Slots

### ISSUE THREAD

**Issue by Blumlaut** [mtadayz/MTADayZ#1]
I find it hard to find the right stuff to change when i want to change the backpack slots, it would be great to make it easier for everyone.

**Comment by 0xCiBeR** [comment]
Sorry didn't get that, can you explain better?

**Comment by Blumlaut** [comment]
I mean, i want to Increase the Slots that you have for the Backpacks, e.g.
Alice Pack: Increase to 26 Slots

**Comment by 0xCiBeR** [comment]
Oh i see. Well it's open source so you can easily edit it, and the current way is working great.
If you have a way to make it easier, please do create a pull request :+1:

**Comment by Blumlaut** [comment]
And that is? I cant find a way how to edit the slots.

**Comment by 0xCiBeR** [comment]
File would be https://github.com/mtadayz/MTADayZ/blob/master/DayZ/handlers/players/server/actions_player.lua#L141
EDIT:
And: https://github.com/mtadayz/MTADayZ/blob/master/DayZ/init/players/spawn_init.lua#L240

**Comment by mtadayz** [comment]
That's not the only file he has to change. In init/spawn_init.lua, there's a function that handles the player's death, and what happens to his/her inventory. He has to change the slots there too.
