### ISSUE TITLE
[HOW] Increase the loot of items

### ISSUE THREAD

**Issue by XyrusPL** [mtadayz/MTADayZ#100]
Hey.
How to increase the loot of items?
I need to edit the file table_loot.lua so?
I want to increase the loot DIY(Wood).

**Comment by 0xCiBeR** [comment]
File table_loot.lua, line 793 change this:
`{"DIY (Wood)",2969,0.5,0,3},`
to this
`{"DIY (Wood)",2969,0.5,0,INSERT HERE YOUR VALUE},`
**Change where INSERT HERE YOUR VALUE to your desired % drop value.**
