### ISSUE TITLE
Vehicle Spawnpoints doesnt work 

### ISSUE THREAD

**Issue by CoreGaming123** [mtadayz/MTADayZ#101]
When i start the server the vehicles doesnt spawn to the server for some reason :(

**Comment by 0xCiBeR** [comment]
Hey! Thanks for contacting us.

Are you using a fresh server install

@CoreGaming123

**Comment by CoreGaming123** [comment]
yes i using a fresh server :)

**Comment by 0xCiBeR** [comment]
Please delete all files in DB Folder.

**Comment by CoreGaming123** [comment]
i fixed :) swap to mysql and add some place to it ;) and the next respawn all works good :dagger:
