### ISSUE TITLE
It is posibble to set the player data to mysql base ?? question

### ISSUE THREAD

**Issue by CoreGaming123** [mtadayz/MTADayZ#102]
i change the sql to mysql :) and i think it is a good idea to set all data to mysql for the easyer acces and it can be placed on a website like webstats :dancer:

**Comment by 0xCiBeR** [comment]
Well, before we went open source we were about to implement it, though the team went really inactive and community members just don't submit patches. Maybe in some future.

**Comment by CoreGaming123** [comment]
i can help you on a scripting :) but i am not a pro :)
