### ISSUE TITLE
When going unconscious while sprinting body temperature keeps rising

### ISSUE THREAD

**Issue by ghost** [mtadayz/MTADayZ#106]
If sprinting while the player falls unconscious, it will keep gaining body temperature until the timer expires.

How to reproduce: 
Get your blood low enough and make sure you are sprinting when you fall unconscious to the ground;
Observe that the temperature should rise as you were still sprinting until you wake up.

Screenshots show the value changing in real time:
![mta-screen_2016-11-23_08-41-56](https://cloud.githubusercontent.com/assets/15793966/20563286/14e6ab28-b16f-11e6-8566-41547a548700.png)
![mta-screen_2016-11-23_08-42-47](https://cloud.githubusercontent.com/assets/15793966/20563291/16f66c50-b16f-11e6-860a-168e67c65aff.png)

**Comment by neves768** [comment]
working on it

**Comment by 0xCiBeR** [comment]
Should be fixed in 	da87af7
