### ISSUE TITLE
It is possible to eat weapons as they were food

### ISSUE THREAD

**Issue by ghost** [mtadayz/MTADayZ#107]
If you eat any food (e.g. sardines), open a loot collision sphere and try to equip any weapon on your inventory, you'll consume the weapon as it were food.

Steps to reproduce:
1- Find or spawn a food item (e.g. sardines, pasta);
2- Find or spawn a weapon (e.g. Makarov PM, DMR);
3- Eat food item (or just right click to show the "Eat sardines" action)
4- Hit any loot collision sphere and open inventory;
5- Try to equip weapon.

The food will be eaten as it should. When the weapon is right clicked while in the colsphere , the action will still be the same as the food (i.e. "Eat sardines"). If the action is issued, the weapon will disappear from the inventory, giving you blood like the food would.

Tested on version:  0.9.7.4a(6ded8e4) and 0.9.8.1a(7c47742).

Screenshots showing examples and debug data on the chat:
![mta-screen_2016-11-23_14-09-49](https://cloud.githubusercontent.com/assets/15793966/20569306/c2a892e6-b186-11e6-9927-da10af44cab9.png)
Right-click on the food to set action.

![mta-screen_2016-11-23_14-10-02](https://cloud.githubusercontent.com/assets/15793966/20569311/c6f2c29a-b186-11e6-8490-d52c8bbbbb6b.png)
On some col, you can see the same action for a weapon in your inventory 

![mta-screen_2016-11-23_14-10-07](https://cloud.githubusercontent.com/assets/15793966/20569313/c897ed96-b186-11e6-9e71-734964fe26ec.png)
Note that eating the weapon gives the player 100 blood, just like the sardines

![mta-screen_2016-11-23_13-10-42](https://cloud.githubusercontent.com/assets/15793966/20568740/9771c112-b184-11e6-8323-ef5776579d7a.png)
Eat away

**Comment by 0xCiBeR** [comment]
Fixed in 0c6c6a15db8828005fe5cf614adf6872d2f39d88 thanks @XyrusPL for the patch,
