### ISSUE TITLE
Dayz Admin pannel remains unusable for vehicles after it respawns

### ISSUE THREAD

**Issue by ghost** [mtadayz/MTADayZ#109]
If you blow/sink some vehicle Dayz admin panel stops working for it after while, fine.
The thing is, after the vehicle spawns, you still can't see the stats of the vehicle or teleport to it.

Steps to reproduce:
Blow up or sink a vehicle in the water;
Wait for it to respawn;
Try to use it in the Dayz vehicles tab.

**Comment by neves768** [comment]
working on it

**Comment by 0xCiBeR** [comment]
Fixed in 4f947a98519879b4bc6c209afb44ba1d1b28f7d5
