### ISSUE TITLE
Ammo Bug?

### ISSUE THREAD

**Issue by Blumlaut** [mtadayz/MTADayZ#11]
A Friend of mine Died, he had 20 Bullets in his double barrel, he respawned, found his body and had about 150 Bullets for some Reason.

**Comment by mtadayz** [comment]
What ammo was it anyway?

**Comment by Renkon** [comment]
Can you reproduce it again? Do you have any sort of proof to be able to
investigate any further?

2015-09-21 18:02 GMT-03:00 L notifications@github.com:

**Comment by Blumlaut** [comment]
1. It was the Slugs for the Double Barrel shotgun
2. Well, my friend made a Screenshot showing his dead body's inventory after he took some

**Comment by mtadayz** [comment]
Should be fixed now. Please give proper feedback so we can either investigate further or close this issue.

**Comment by Blumlaut** [comment]
Seems to be fixed, tried to reproduce it with a friend, nothing worked.
