### ISSUE TITLE
consume_player causing lots of error

### ISSUE THREAD

**Issue by turret001** [mtadayz/MTADayZ#110]
Screenshot of the console:  
![image](https://cloud.githubusercontent.com/assets/24281147/20773587/2d9aa650-b75b-11e6-94f8-71031198e8fb.png)

screenshot of the lines that causes error:

http://i.hizliresim.com/nj7EzM.png

**Comment by ghost** [comment]
How to reproduce?

**Comment by 0xCiBeR** [comment]
8eb305b should have fixed those warnings.
