### ISSUE TITLE
Vehicle lag when spawn in admin panel

### ISSUE THREAD

**Issue by InvolutionzEdge** [mtadayz/MTADayZ#112]
Vehicle lag when spawn or drive

**Comment by 0xCiBeR** [comment]
Could you please explain this issue better?

**Comment by InvolutionzEdge** [comment]
i use script vehicle store for buying when drive the car fps drop or lag

**Comment by 0xCiBeR** [comment]
We do not support third party extensions, there may be a problem with the custom vehicle spawning resource that may be giving FPS spikes or performance issues.
