### ISSUE TITLE
Zombies keeps spawning then disappears

### ISSUE THREAD

**Issue by christiansenandi** [mtadayz/MTADayZ#116]
i just updated to latest release. and the zombies spawns for a moment then disappears. and if i manage to kill one it dissappears again?

Is this normal behavior?

**Comment by 0xCiBeR** [comment]
Zombies should spawn based on movement.

**Comment by christiansenandi** [comment]
Hi Kevin.

Ok, but I am not sure how that explains what happens. Zombies disappear on their own even if im running around them, they are only visible for about 5-10 sec then gone.. and if I shoot and kill one, it just disappears, no body left what so ever :-) 

Best regards 
Andi.
