### ISSUE TITLE
[OFF-GIT] [WEBSITE Related] Website launch date?

### ISSUE THREAD

**Issue by neves768** [mtadayz/MTADayZ#119]
When we can see mtadayz.org back to up and running? (domain is lost?)

**Comment by 0xCiBeR** [comment]
I could get it back up and running.. But will it be helpfull?

**Comment by neves768** [comment]
The domain still is active? (host free + paid domain = happiness =P)
I think nope so much, only for "marketing" purpose. MTA:DayZ don't need it, but not all people knows about the new git version. I'm seeing servers still with the old 0.5.5 version.
You can also add a MTA:DayZ variation list (modifications of MTA DayZ) that people helps to send

**Comment by 0xCiBeR** [comment]
I'm the owner of the domain. Payed hosting is not a problem as i run a hosting company. Please contact me on MTA:SA forums for further details: https://forum.mtasa.com/profile/35053-ciber/
