### ISSUE TITLE
Cars with right coordenates on the script but no cars on the server

### ISSUE THREAD

**Issue by CarlosNunes1999** [mtadayz/MTADayZ#18]
Hi when i saw vehiclecfg there is a lot of coordenates of the cars spawns but when someone go to that coordenates there is no car and in f7 admin option there is no cars too......

No error on machine..... I trie debugscript 3 but there is no error too....

Someone can help

**Comment by mtadayz** [comment]
1) Stop DayZ
2) Delete the vehicleManager (go to server console and enter this: delaccount vehicleManager
3) Get a fresh vehicles.db (from the GitHub repository), and replace your old one
4) Start DayZ

**Comment by CarlosNunes1999** [comment]
Working now thanks a lot......
