### ISSUE TITLE
Restart

### ISSUE THREAD

**Issue by Synix28** [mtadayz/MTADayZ#19]
If i restart the Server, and join, login. I die at the spawing....

PLEASE FIX IT :)

**Comment by 0xCiBeR** [comment]
Are you in combat at the moment you restarted the server?

**Comment by Synix28** [comment]
No

**Comment by Synix28** [comment]
Its for everyone on the Server :)

And where's the internal.db??? to install

**Comment by 0xCiBeR** [comment]
Please refer to our forums for more help as you do not provide sufficient data for a issue report. https://mta-dayz.org/forum

**Comment by Synix28** [comment]
k

**Comment by Synix28** [comment]
CAN'T REGISTER HELP!!! THIS SHITY Verification sucks

**Comment by Blumlaut** [comment]
Unbelievable, It clearly says what you have to do, its a simple task.
