### ISSUE TITLE
No m4 or ak47 and map texture bugged

### ISSUE THREAD

**Issue by CarlosNunes1999** [mtadayz/MTADayZ#2]
Hi i install this gamemode yesterday and i think is realy amazing.......
But i have some problems like m4a1 and ak dont exist i trie spawn and create and dont work dont show in inventory and the map is like with no texture

**Comment by mtadayz** [comment]
How did you try to spawn the items? With GIP? dayzadmin? Because neither have the new weapons. You'd have to manually use setElementData. Also, what map texture?

**Comment by Loki214** [comment]
I think he is talking about the night mode. People who's PC do not support the night shader (old PC) see the whole map gray so I you have to disable night in the dayz config.

**Comment by mtadayz** [comment]
Ah, I see. Will add a configurable option then.

**Comment by CarlosNunes1999** [comment]
Thanks i dont see gray i see like sand just yellow with no texture.....
And i test with f7 addon incluid on the gamemode and dont work dont spawn m4.....

**Comment by CarlosNunes1999** [comment]
A image of my screen.....
http://i.imgur.com/2VdQPLh.png
1 more thing when i install version 9.5.6 and i start the server says is the version 9.5.3 can you says the link of the newest version?

**Comment by mtadayz** [comment]
Like I said, neither GIP nor DayZAdmin have the new weapons. Will have to add them sometime later. Also, if you download the newest update from the master branch on GitHub, you'll get a configurable option for the night system. You can turn it on/off in cfgClient. By default, it's set to "true". If you want to disable it, set it to "false" (no quotes).

**Comment by CarlosNunes1999** [comment]
K thanks 1 more time the files are realy good.....

**Comment by CarlosNunes1999** [comment]
The config is disable but i have night its like disable in script and active in game why????
-- MISC
gameplayVariables["enablenight"] = false -- Whether or not the night should be darker - DEFAULT: true - SET TO false to disable - remember you need to set it in editor_server.lua too.

I cfg server is false too

**Comment by mtadayz** [comment]
Download the newest master branch.
If you don't get it, go to handlers/world/client/night and open c_night.lua. Scroll down to...

function night_init()

...and add this as the first line of the function:

if not gameplayVariables["enablenight"] then return end

That will turn night off, if the variable is set to false.

**Comment by CarlosNunes1999** [comment]
Hey but the ak and the m4 i think isnt the problem of GiV becouse when i use the addon craft to craft a m4 dont work..... i craft the m4 and dont aparead on my gear....
And if i kill zombies with ak or m4 they when they die they dont show on floor and need like 25 bullets to kill 1

**Comment by mtadayz** [comment]
Crafting is bugged, the blueprints haven't been renamed yet.

**Comment by CarlosNunes1999** [comment]
and why i kill zombies i need 25 shoots to kill a zombie and their dont loot or show on floor?
And the m4 or ak have no texture

**Comment by CarlosNunes1999** [comment]
Ok now i know why that appenned.... I dont script a long time i thaught  the id of the weapons was the original but you change so the addon of give weapons dont have the name of the new weapons,.....

1 more thing why when someone damage on me the screen is black?

**Comment by mtadayz** [comment]
Usually, it's supposed to turn gray, but if you have a potato as a PC, the shader will just make it black...
