### ISSUE TITLE
ArmA II Style Chatbox

### ISSUE THREAD

**Issue by mtadayz** [mtadayz/MTADayZ#32]
Should be like this:

http://i.ytimg.com/vi/oEJ6sl78Juk/maxresdefault.jpg

**Comment by CarlosNunes1999** [comment]
if you get that texture for mta how would be amasing

**Comment by mtadayz** [comment]
Added with Commit https://github.com/mtadayz/MTADayZ/commit/9b55534d47f222cacf986ce85428a871c6880200

Needs some outside testing, feedback is much appreciated.

**Comment by Blumlaut** [comment]
Maybe make it a bit Smaller(?)
I'm running at 1366x768 and the chatbox is just too big in my Opinion, also, system messages are displayed Red, but the closing " isn't Red.
