### ISSUE TITLE
FPS-Drop Spikes

### ISSUE THREAD

**Issue by Blumlaut** [mtadayz/MTADayZ#33]
After further testing me and 2 friends ( we all have different specs and a different OS) we were all experiencing weird FPS Spikes, wich appear every couple of seconds, i already tested and disabled all resources except for Slothbot and DayZ, and DayZ MUST be the problem here, tho i don't know whats causing it.

**Comment by mtadayz** [comment]
I pushed an update (https://github.com/mtadayz/MTADayZ/commit/9b55534d47f222cacf986ce85428a871c6880200), can you tell me if that increased performance for you and your friends?

**Comment by Blumlaut** [comment]
I tested it alone right now and it seems that it really improved overall performance, i still have small lagg spikes but these arent as game-breaking.

**Comment by mtadayz** [comment]
Are they less frequent now? Like, every 30 seconds?

**Comment by Blumlaut** [comment]
No, less frequent and shorter, like, every 6 seconds(?)

**Comment by mtadayz** [comment]
Pushed another update just now, any better?

**Comment by Blumlaut** [comment]
It didn't really fix anything, i still have the same stutters as before.

**Comment by 0xCiBeR** [comment]
This could actually be a timer. Timers cause strain on client and are not recommended.

**Comment by ghost** [comment]
The latest commit (5069f4f) seems to have solved the problem for me. Meet you still have the problem?

**Comment by ghost** [comment]
Hello,

After several checks, I consider the problem as solved. If you encounter a problem, please open a issue.

Rémi
