### ISSUE TITLE
Add new car but he dont spawn on the server

### ISSUE THREAD

**Issue by CarlosNunes1999** [mtadayz/MTADayZ#35]
Hey i just add a new car mesa more expecificly and when i add he dont spawn on the server
I add and i got this error
DayZ\init\vehicles\vehicles_init.lua:276: bad argument #1 to 'ipairs' (table expected, got nil)

Changes i make:

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Vehicle_init.lua

Mesa_Spawns = gameplayVariables["mesaspawns"]

for i,veh in ipairs(Mesa_Spawns) do
        local number = math.percentChance(veh[7],4)
        if number and number >= 1 then
            v_counter = v_counter+1
            local x,y,z = veh[1],veh[2],veh[3]
            local rX,rY,rZ = veh[4],veh[5],veh[6]
            veh = createVehicle(500,x,y,z,rX,rY,rZ)
            vehCol = createColSphere(x,y,z,3)
            attachElements ( vehCol, veh, 0, 0, 0 )
            setElementData(vehCol,"parent",veh)
            setElementData(veh,"parent",vehCol)
            setElementData(vehCol,"vehicle",true)
            setElementData(vehCol,"MAX_Slots",50)
            --Engine + Tires
            local tires,engine,parts,scrap,glass,rotary,name = getVehicleAddonInfos (getElementModel(veh))
            setElementData(vehCol,"Tire_inVehicle",math.random(0,tires))
            setElementData(vehCol,"Engine_inVehicle",math.random(0,engine))
            setElementData(vehCol,"Parts_inVehicle",math.random(0,parts))
            setElementData(vehCol,"Scrap_inVehicle",math.random(0,scrap))
            setElementData(vehCol,"Glass_inVehicle",math.random(0,glass))
            setElementData(vehCol,"Rotary_inVehicle",math.random(0,rotary))
            setElementData(vehCol,"vehicle_name",name)
            --vehicle_indentifikation  
            setElementData(vehCol,"spawn",{500,x,y,z})
            --others
            setElementData(vehCol,"fuel",10)
            setElementID(vehCol,tostring(v_counter))
            setElementHealth(veh,math.random(300,1000))
            exports.DayZ:saveLog("Vehicle "..getVehicleName(veh).." has been created (ID: "..getElementID(vehCol)..")\r\n","debug")
        end
    end
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

table_vehicles.lua

vehicleAddonsInfo = {
{500,4,1,1,0,0,0,"C104 Jeep",3,50,100,"Mesa"},

vehicleFuelTable = {
{500,100},

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

CfgVehicle.lua

gameplayVariables["mesaspawn"] = 
{
{2486.1872558594, -1670.3182373047, 13.335947036743},
{2485.4575195313, -1675.8995361328, 13.335947036743},
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Where is the error?

**Comment by mtadayz** [comment]
In cfgVehicles. You wrote "mesaspawn", but it has to be "mesaspawns".

Also, you are missing 4 more values: rotationX, rotationY, rotationZ and chanceToSpawn. It should look like this:

{2486.1872558594, -1670.3182373047, 13.335947036743,0,0,0,75},
{2485.4575195313, -1675.8995361328, 13.335947036743,0,0,0,75},
