### ISSUE TITLE
No Internet

### ISSUE THREAD

**Issue by mtadayz** [mtadayz/MTADayZ#44]
I don't have any proper internet, and won't have until the end of October, so any issues, pull requests, suggestions and/or questions you're having are to be directed to CiBeR (ciber96), who's also in charge of accepting or denying pull requests until I'm back.

Don't let this project die in my absence!

**Comment by 1B0Y** [comment]
Phone that ISP, tell them they're s***!

**Comment by Renkon** [comment]
You shall not die!
