### ISSUE TITLE
Teleport Hack

### ISSUE THREAD

**Issue by imCEASER** [mtadayz/MTADayZ#49]
Just my friend was playing, fell from a bridge and was banned for teleport hack

**Comment by Renkon** [comment]
Did this happen after latest merge?

2015-10-21 16:32 GMT-03:00 imCEASER notifications@github.com:

**Comment by neves768** [comment]
with a jump? i'ill check it
@Edit
The problem: The player is banned when he was killed (he's teleported here)
I'ill make a fix and a new test (and i'ill record a video of my test)

**Comment by 0xCiBeR** [comment]
Should be fixed now 503bd7bf6cd9d65406b3619a10796b6014ff1fb3
