### ISSUE TITLE
Scoreboard.lua:12 attempt to index field '?' ( nil )

### ISSUE THREAD

**Issue by Blumlaut** [mtadayz/MTADayZ#5]
Shows on Debugscript when a player is joining but not logged on.

**Comment by mtadayz** [comment]
Yeah, that happens. It's nothing major though, just the script trying to get a particular element data, but is unable to do so since the player in question doesn't have it. You can safely ignore it. Or attempt to fix it yourself and make a pull request.

**Comment by Renkon** [comment]
The easiest workaround would be to pre-check it's not a nil value.

**Comment by 0xCiBeR** [comment]
411d3e6383c1f3fcbf64e9030fd298e563ec0a6e should hold a check on that to avoid nil.
