### ISSUE TITLE
Skin bug.

### ISSUE THREAD

**Issue by Stifler98** [mtadayz/MTADayZ#52]
Hello guys! i have a problem with the weapon skins, i see the correct skin on the weapon, but the other players don't see it (They see the default skin) or see another skin not that what in my hands.
So: i have got a cz550 skin, but the other player see the m24 skin or another skin. Please help me how to fix it.
-Sorry for my bad english :)

**Comment by Blumlaut** [comment]
The Problem here is, multiple weapons are used on one weapon skins, the stats etc just get adjusted,  you cant really fix it, and you cant replace models of specific elements yet..
