### ISSUE TITLE
Arma 2 chat

### ISSUE THREAD

**Issue by KaSkA3eR** [mtadayz/MTADayZ#53]
How can i change position of chat to left up corner?

**Comment by Renkon** [comment]
You can't programatically change the position of the chatbox. However you
can make a custom chat (which will take a long work to do), or you can edit
your personal settings to place the chatbox in the desired position.

2015-12-30 16:06 GMT-03:00 Filip Czechowicz notifications@github.com:

**Comment by KaSkA3eR** [comment]
I mean arma 2 style chatbox but its  not actual now. I moved my custom gps to left upper corner.
