### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ksantus12** [mtadayz/MTADayZ#56]
Can i edit this game mode and use him on my serwer ?

**Comment by Blumlaut** [comment]
yes.

**Comment by Ksantus12** [comment]
I can do whatever i want with this script ? Are there any restrictions ?

**Comment by itslewiswatson** [comment]
Read "License" in README.md.

**Comment by 0xCiBeR** [comment]
You must keep copyright with the developers names and also you can't sell all or any part of this gamemode. As @nokizorque said, read License in README.md for full info.
