### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Ksantus12** [mtadayz/MTADayZ#57]
Hi, wiki for DayZ is not working. So, I have a question. This script is working with mysql ?

**Comment by Renkon** [comment]
no

2016-01-26 14:02 GMT-03:00 Ksantus12 notifications@github.com:

**Comment by rasitds** [comment]
The database can be easy to change. Vehicles, Tents and need to sort the data in Character.

**Comment by 0xCiBeR** [comment]
It's not working with MySQL as renkon mentioned. We were though working on a possible integration at the latest builds. Check some of the commits.
