### ISSUE TITLE
What does it mean ?

### ISSUE THREAD

**Issue by Ksantus12** [mtadayz/MTADayZ#58]
http://scr.hu/7zh5/geuul
What does it mean ?

**Comment by 1B0Y** [comment]
I believe that this was one of my backup features that occurs over a period of time. Can't exactly remember what it was used for, but I think it was something to do with MySQL integration.

**Comment by 0xCiBeR** [comment]
Well link was down when I tried to see the screenshot. I'd go with Jboy's approach as we were trying to get MySQL integration to work at the final stages of closed source.
