### ISSUE TITLE
Error when damaging player / getting Damaged

### ISSUE THREAD

**Issue by Blumlaut** [mtadayz/MTADayZ#6]
damage_player.lua:77: attempt to perform arithmetic on global 'damage' ( nil )

Tried with 3 Weapons, all the same result.

**Comment by mtadayz** [comment]
What weapons?

**Comment by Blumlaut** [comment]
I tried the Lee Enfield, Knife and a Pistol(forgot it's name)

**Comment by mtadayz** [comment]
Should be fixed with this commit:

https://github.com/mtadayz/MTADayZ/commit/251424416b430fb7e3c4756e344f4684452ba793
