### ISSUE TITLE
still fps drop/spikes/lags

### ISSUE THREAD

**Issue by ezglggwp** [mtadayz/MTADayZ#60]
When playing this gamemode, after 1-2seconds the game just shutters/drops fps spikes.

Can anyone finnaly fix it?

Remove timer or anything..

**Comment by ghost** [comment]
I'm currently trying to find the problem. I have the same FPS issue.

**Comment by ghost** [comment]
Dear survivor,

The latest commit (5069f4f) seems to have solved the problem for me. If you encounter the problem again, please report it here : https://github.com/mtadayz/MTADayZ/issues/33

Rémi
