### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Brokengunman** [mtadayz/MTADayZ#61]
can other people add their own new weapons on this update(0.9.6a)? if yes can you tell me how because i was trying and it didn't work.

**Comment by ghost** [comment]
Dear Survivor,

What file did you try to change to add the weapon ?

Rémi

**Comment by Brokengunman** [comment]
i changed the Table files,gui,and handlers

**Comment by ghost** [comment]
Ok. I invite you to base a weapon as the Lee Enfield is to do a complete search in your server file (CTRL + SHIFT + F on Sublime Text 3, CTRL + F for an simple search).

The search returns me 13 results (84 "Lee Enfield" words) in the following files :
- **[addons]\addon_gip\gip_c.lua**
- **DayZ\group\group.slua**
- **DayZ\gui\gear\functions_gear.lua**
- **DayZ\gui\gear\language_gear.lua**
- **DayZ\handlers\players\server\loot_player.lua**
- **DayZ\models\loadskins.lua**
- **DayZ\models\weaponswitch.lua**
- **DayZ\tables\table_general.lua**
- **DayZ\tables\table_loot.lua**
- **DayZ\tables\table_player.lua**
- **DayZ\tables\table_tents.lua**
- **DayZ\tables\table_vehicles.lua**
- **dayzadmin\dayzadmin_gui.lua**

You just have to take example from that to create your own weapon. Search, copy / copy each line of the Lee Enfield, paste below and change the name and other variable. ;-)

Rémi

**Comment by 0xCiBeR** [comment]
Also remeber to add it in every language you will use, as it'll generate errors if you don't do this step.

**Comment by ghost** [comment]
The issue is now closed. **Reason:** Considered resolved. If you encounter a new problem, open a new issue.
