### ISSUE TITLE
adding Weapons

### ISSUE THREAD

**Issue by JJohncena1738** [mtadayz/MTADayZ#64]
this is optional but can you guys make it easier to add weapons into the server if possible

**Comment by ghost** [comment]
Unfortunately it will be difficult to make this easier. We will see in the future. For the moment, you need to edit the following files to add a weapon : (taking as reference the weapon "Lee Enfield")
- **[addons]\addon_gip\gip_c.lua**
- **DayZ\group\group.slua**
- **DayZ\gui\gear\functions_gear.lua**
- **DayZ\gui\gear\language_gear.lua**
- **DayZ\handlers\players\server\loot_player.lua**
- **DayZ\models\loadskins.lua**
- **DayZ\models\weaponswitch.lua**
- **DayZ\tables\table_general.lua**
- **DayZ\tables\table_loot.lua**
- **DayZ\tables\table_player.lua**
- **DayZ\tables\table_tents.lua**
- **DayZ\tables\table_vehicles.lua**
- **dayzadmin\dayzadmin_gui.lua**

13 files for 84 "Lee Enfield" words.

**Comment by JJohncena1738** [comment]
Thanks I hope the development never stops :)

**Comment by ghost** [comment]
It's extremely difficult right now, but I'll do my best to update MTA:DayZ. I have a lot of things to do ! :)
