### ISSUE TITLE
first person

### ISSUE THREAD

**Issue by JJohncena1738** [mtadayz/MTADayZ#66]
I don't know if it's just me or other people too but i think the first person mode is bugged you cant turn your camera and cant aim anywhere

**Comment by Wisam97** [comment]
haha i was just about to post somthing like that.. i do have this problem too
EDIT: Now im gonna play for a while and try to find as much bugs as possible and post them at once

**Comment by ghost** [comment]
Dear Survivor,

Thank you for the report. We'll check that.

Rémi

**Comment by ghost** [comment]
It's now added on Trello : https://trello.com/c/8336g66m/12-first-person-issue
