### ISSUE TITLE
Crafting bug

### ISSUE THREAD

**Issue by Wisam97** [mtadayz/MTADayZ#67]
So i started testing the gamemode and hunting for bugs today and i just found a bug in the inventory system:
I gave my self M4 blueprint and the required parts then i started crafting, but when the bar reached to the end i got a spamming message saying "The item has been crafted!" and the completed bar is still showing and i can't use the blueprint anymore.

**Comment by ghost** [comment]
Dear Survivor,

Thank you for the report. We'll check that.

Rémi

**Comment by ghost** [comment]
It's now added on Trello : https://trello.com/c/zGJU6KRx/11-crafting-bug
