### ISSUE TITLE
chat bug

### ISSUE THREAD

**Issue by JJohncena1738** [mtadayz/MTADayZ#69]
whenever i type something like /pm or /add admin or other stuff it says access denied every time even if its a custom resource

**Comment by ghost** [comment]
Dear survivor,

You have set the administrator rights to the resource DayZ ? Like this: http://bit.ly/298cTUi
To do that, the explanations are available here: http://bit.ly/28SdMDB

Also make sure you put admin rights to your account.

Rémi

**Comment by JJohncena1738** [comment]
I did that but still the same thing here is what it says

WARNING: [DayZ-MTA]\DayZ\handlers\world\server\chat.lua:55: Access denied @ 'executeCommandHandler'

**Comment by ghost** [comment]
Can you send me your ACL file ? I need check it.

**Comment by JJohncena1738** [comment]
[ACL.txt](https://github.com/mtadayz/MTADayZ/files/336167/ACL.txt)

**Comment by ghost** [comment]
Thanks. Everything is good, no errors. I will do checks in the code soon.

**Comment by JJohncena1738** [comment]
Sorry to bother you but did you check the code because when i try to type /kill,/pm,/add admin,/start, etc... it says Access denied

**Comment by ghost** [comment]
Did you try to send commands via the "f8" without "/" ? For me, the "start" command for example works well.

**Comment by JJohncena1738** [comment]
Thanks it worked cant believe i forgot about that xD

**Comment by ghost** [comment]
Haha congratz !
