### ISSUE TITLE
mod help

### ISSUE THREAD

**Issue by Stifler98** [mtadayz/MTADayZ#70]
Hello guys!
I found an older mod here:  https://mta-dayz.org/  at 6 months, but now is not working.
I would like to download the older mod, because the newest mod (here) too  "developed" for me.
So i couldn't download the older mod, but i need. So can u give me an older mod?
I need the 0.8 mod . Pls help me :3
I know, i know.. the internet has lot of mods, but there's very bad or unusabble.
Pls help me ! :)

**Comment by ghost** [comment]
Dear Survivor,

I do not want to send you older versions because they contain many bugs and uses deprecated functions.

You can find the latest update of MTA:DayZ here: https://github.com/mtadayz/MTADayZ/releases

I hope you understand,
Rémi
