### ISSUE TITLE
Bodys disappear

### ISSUE THREAD

**Issue by JJohncena1738** [mtadayz/MTADayZ#71]
When players die their body disappears and cant loot them

**Comment by ghost** [comment]
Dear Survivors,

Thanks for the report. I assign this issue for myself, I gonna check it !

Thanks,
Rémi Gaffet

**Comment by ghost** [comment]
For a body appear, must play time (alivetime) is greater than 10. Except that the value "alivetime" is updated every hour, so it would take 10 hours of play for the body of a killed player appears.

**Comment by ghost** [comment]
Fixed ! (https://github.com/mtadayz/MTADayZ/commit/d2db21d1914320b6988f18b6ae22065207ebe544)
