### ISSUE TITLE
Questions about concussion and infection system

### ISSUE THREAD

**Issue by JJohncena1738** [mtadayz/MTADayZ#72]
does concussion last for a certain amount of time? if yes can you tell me how to change it or does it stay till someone gives you epi-pin?

Edit: sometimes concussion lasts forever i don't know if its a glitch

And infection sometimes stay even when you use Antibiotics (within spawning)

**Comment by ghost** [comment]
This is related to the fact that you have not a lot of blood. It's not an bugs/glitch.
