### ISSUE TITLE
no way to input Chinese

### ISSUE THREAD

**Issue by MrWang99** [mtadayz/MTADayZ#73]
Anyway I can not help by T input Chinese

**Comment by ghost** [comment]
Hello,

Can you explain your problem? I understand anything.

Rémi Gaffet

**Comment by Blumlaut** [comment]
He was referring to the chatbox as he cannot enter chinese characters

**Comment by 0xCiBeR** [comment]
Could you provide some feedback? as in for example when you send the text, does it show on the console?
