### ISSUE TITLE
gps and map problem

### ISSUE THREAD

**Issue by JJohncena1738** [mtadayz/MTADayZ#79]
the GPS and map doesn't show custom blips or player blips and it's annoying because im trying to add addon_airdrop and it needs custom blips so players can find it on map or gps and on the map the player.png shows the wrong way

any suggestions? 

Image:
![mta-screen_2016-07-08_17-46-58](https://cloud.githubusercontent.com/assets/20143962/16705098/3297e430-4535-11e6-9d59-915f00670e60.png)

Image:
![mta-screen_2016-07-08_17-57-53](https://cloud.githubusercontent.com/assets/20143962/16705149/7ccf5438-4536-11e6-922b-f2d6d8cd1867.png)

**Comment by Wisam97** [comment]
Can you please share the airdrop addon?

**Comment by JJohncena1738** [comment]
sure here you go :)

http://www.mediafire.com/download/cdq59bxk0kkf0ig/airdrop-jjohncena1738.rar

**Comment by Wisam97** [comment]
Thanks alot man, it works!
And for the blip problem, the file that handles the map, gps and blips is at DayZ\gui\gear\hud_gear.lua
If you know some lua you can edit the file and add a custom blip for the airdrop.. i'll try to do it too and if i did it i'll post here

**Comment by 0xCiBeR** [comment]
Are you setting the elementData for the custom blip? Element data should be: customIcon https://github.com/mtadayz/MTADayZ/blob/master/DayZ/gui/gear/hud_gear.lua#L207

**Comment by 0xCiBeR** [comment]
No feedback provided for over a month. Closing this. In case of further problems open a new issue
