### ISSUE TITLE
How i add cars to the server? 

### ISSUE THREAD

**Issue by RafaMy** [mtadayz/MTADayZ#80]
wanted to add a bullet and a infernus
which file? 
My dayz version is 0.9.8.1

**Comment by Pietr** [comment]
Use notepad++ and CTRL+F.

**Comment by RafaMy** [comment]
that don't help '-' what it's the file ?

**Comment by ghost** [comment]
Hello,

For now, there is no documentation to help server owners to add vehicles. Articles will be published soon on the wiki GitHub project. We'll have to wait.

Rémi Gaffet

**Comment by ghost** [comment]
The issue is now closed. **Reason:** Considered resolved. If you encounter a new problem, open a new issue.
