### ISSUE TITLE
how do I put normal GPS and the map and chat?

### ISSUE THREAD

**Issue by RafaMy** [mtadayz/MTADayZ#81]
how do I put normal GPS and the map and chat?

**Comment by Pietr** [comment]
Please don't help. Let alone teach. Because later it will be a lot of such questions.

**Comment by RafaMy** [comment]
ok

**Comment by RafaMy** [comment]
thank u for the help -.-

**Comment by xboxxxxd** [comment]
ciber96, i want to design & improve the MTA:DayZ GUI's, Several of them, PM me or contact me, Facebook: Djni Wlk, (BTW: i didnt know a other way to quickly get any contact so i put it on here :| )

EDIT: A Preview of a Already Testing Design GUI for Encampment Panel:
![mta-screen_2016-07-12_13-01-11](https://cloud.githubusercontent.com/assets/6675843/16781603/e9441b24-4830-11e6-9235-83ee912b2290.png)
![mta-screen_2016-07-12_13-01-14](https://cloud.githubusercontent.com/assets/6675843/16781604/e9488b14-4830-11e6-9624-291053462d8f.png)

**Comment by 0xCiBeR** [comment]
This issue is closed. Please post a new one.
