### ISSUE TITLE
Request/Invite: Interested in a GUI Designer?

### ISSUE THREAD

**Issue by xboxxxxd** [mtadayz/MTADayZ#83]
Hello there MTA:DayZ Dev's,
I am interested to design the GUI's for the whole Gamemode, Resource's, etc.
Ive seen a Request and/or one of you dev's where talking about it needs a better GUI Design,
So i want to get into this, and make the GUI's,
It may happen that one of you have to patch the GUI's into the script's, i will check up later if i am prepared to do it myself tho, some are messy scripts...

Anyways, Is there room for a New GUI Designer?, If so,
Ask me, i am for now open for it, i even made the base GUI for the 'Encampment System'!,
Some Screenshot's down below..

Greetings; xboxxxxd.

Screenshot's, Base - Encampment System:
![encampment panel gui core](https://cloud.githubusercontent.com/assets/6675843/16802591/5c1ad48c-48b6-11e6-9a15-c2241561e13e.png)
![encampment panel gui management](https://cloud.githubusercontent.com/assets/6675843/16802592/5c1d10e4-48b6-11e6-93ba-75feb7fed710.png)

**Comment by ghost** [comment]
Hello,

MTA:DayZ is an open-source project, you can contribute on it. More information here : https://guides.github.com/activities/contributing-to-open-source/

Thanks,
Rémi Gaffet

**Comment by xboxxxxd** [comment]
If the resource was made from scratch by myself, i would have done it myself, but as in this case, i won't, i geus i am lazy, but that doesnt mean i won't finish the GUI itself, Here's The full Finished Encampment Improved GUI Script (Without Commands, Toggle's, etc):
[GUI_DayZ_FULL_EP_GUI_2016-7-13_8-3.txt](https://github.com/mtadayz/MTADayZ/files/361920/GUI_DayZ_FULL_EP_GUI_2016-7-13_8-3.txt)

Update the Dayz/group/group.lua only when patching this into it.

BTW, As i sayd in the first comment, I make GUI Designs, and not the Scripts :/,
Just saying.

**Comment by ghost** [comment]
Very good. I'll watch it, thank you for your contribution.

**Comment by xboxxxxd** [comment]
Update GUI: i gonna use a custom GUI-LIB in the future for the GUI of MTA:DayZ,
So you can easly load different styles and maby if i have time for it, a settings menu for setting your GUI's (For Players) to DayZ Style, Arma II Style, MTA Style, Several Color Styles, Etc..

Greetings.xboxxxxd

**Comment by xboxxxxd** [comment]
Testing some GUI Function's, Like Texture's, Making first a functional Admin Panel, then i will after that Work on the MTA:DayZ Panel!.

Greetings.xboxxxxd

**Basic idea i kinda wanna use with MTA:DayZ, Screenshot's:**
_Left, Middle (Options), Right - Admin Panel;_
![mtadayz design showing - options](https://cloud.githubusercontent.com/assets/6675843/16984758/ff9d4c1e-4e30-11e6-8eb6-29aa3dc68fc7.png)

_Middle (Players) Functions, - Admin Panel:_
![mtadayz design showing - players](https://cloud.githubusercontent.com/assets/6675843/16984769/0c501446-4e31-11e6-87f5-1fccfe686498.png)

**Comment by ghost** [comment]
It's nice ;)

**Comment by 0xCiBeR** [comment]
Well i'm glad you are intrested in contributing to the project. At first glance it seems nice what you have made, tho for us to be organized you must create an individual issue for each resource or update you make and make the apropiate pull request. I'm eager to see some good guis coming our way.

Sincerly, CiBeR.

**Comment by xboxxxxd** [comment]
ciber96, Thanks, that's all i have to say, further,
individual issue's, oright, i wil give it when it's finishe'd in a new issue :).

Greetings.xboxxxxd
