### ISSUE TITLE
Crashed-Heli Exploding on PlayerJoin.

### ISSUE THREAD

**Issue by xboxxxxd** [mtadayz/MTADayZ#84]
today i got killed when i joined the official server, the heli killed me instantly,
and it seems it does explode on a login event..

Greetings.xboxxxxd

**Comment by ghost** [comment]
Dear xboxxxxd,

Thank you for the report. Thank you for helping us improve MTA DayZ. It is a well known problem of GTA San Andreas. We'll see if there are solutions to resolve it.

Rémi Gaffet
