### ISSUE TITLE
Idea for F11 Map item: Locate nearby Looting place's!.

### ISSUE THREAD

**Issue by xboxxxxd** [mtadayz/MTADayZ#88]
So sometimes, the Lootings are placed on a place where you are hard to se them, well..
It sometimes places the item view of the looting inside a wall, so it could be abit easyer to have a map that has actually a function instead of only being a map only..

With that sayd, Somthing like a 70/90 Steps arround the Player it can Show where the lootings are,
and maybe, use a Question mark for it, instead of telling the map it's a looting package,
The reason for a Question mark is so you could if wanted add a vehicle, a dead body (player that died)
also with a Question mark, or an Icon telling you: Hey!, Pay Attention, somthing is overhere!..

Greetings.xboxxxxd

**Comment by ghost** [comment]
Dear Xboxxxxd,

Thanks for the feedback. It's a great idea. :)

Rémi Gaffet

**Comment by 0xCiBeR** [comment]
Well i'll leave this open, but in my opinion it totally impacts in a negative way the survival mode. Waiting for feedback.

**Comment by ghost** [comment]
I do agree that we need a clearer way of spotting the loot points. Though I was thinking about something more immersive, perhaps like carefully positioned and scaled items, or some way to draw attention to them.
