### ISSUE TITLE
ERROR: Handler, status_player.lua, Spamming.

### ISSUE THREAD

**Issue by xboxxxxd** [mtadayz/MTADayZ#89]
Latest ERROR popping-up:
**[2016-07-13 09:30:07] ERROR: DayZ\handlers\players\server\status_player.lua:202: attempt to compare number with boolean**

What does this Error?:
I don't have any idea what it doe's, but i know it has to do with the status, well it's clearly shown in error!.

Possibility what Caused this Error!?:
1. Older kind of code, (a mta update changed something).
2. Script Combination conflict's from the latest MTA:DayZ Release's.
3. A addon is causing this Error, Maby Antiglitch or somthing, as it is the latest addon of the list.
4. i dunno!? xD.

Serverlog (Made Some things Private!), And some other error's aswel, including restarting give's DayZ Long waiting time:
**_[server.txt](https://github.com/mtadayz/MTADayZ/files/366064/server.txt)_**

Greetings.xboxxxxd

**Comment by Blumlaut** [comment]
possible fix, see [this pull request](https://github.com/mtadayz/MTADayZ/pull/90)

**Comment by 0xCiBeR** [comment]
This was fixed in: 02e9a127a215d77cd417179ebf4599f1d971f141
