### ISSUE TITLE
Zombies Sometimes Spawn Inside / Ontop / Infront of the Car

### ISSUE THREAD

**Issue by Blumlaut** [mtadayz/MTADayZ#9]
Wich is annoying and just breaks the Point of having driveable cars.

Reported by one of my Users

( Forum post: http://phoenix-gaming.tk/viewtopic.php?id=75 )

**Comment by mtadayz** [comment]
Fixed with commit https://github.com/mtadayz/MTADayZ/commit/9b73d5e236d000de605fae508b5612026bcbc460, zombies won't spawn anymore as long as the local player is inside a vehicle. This means zombies can still spawn if a vehicle's occupant gets out and runs around outside.
