### ISSUE TITLE
Crosshair help

### ISSUE THREAD

**Issue by Stifler98** [mtadayz/MTADayZ#91]
Hello!
How to hide the weapon model when i aiming?
I successfully hide the player model, but i can't hide the weapon model.
I didn't find any "problem solving" on the internet.
Can u help me? I need you ! :)

Sorry for bad english translation.

**Comment by xboxxxxd** [comment]
If you mean to be in 'First Person Mode' (O on keyboard), It isnt finished yet,
also: the 'First Person Mode' does not spin arround 360 Degrees, Dev's, it's an important thing to fix.
Right now it only spin's 180 Degrees as far i know.

also just an idea for this problem: Maby Live-Draw the weapon on screen with screenW/screenH and make it follow the Middle of the screen with a smoothness effect. (Could come in handy when having custom weapon models in 'First Person Mode'!.

Greetings.xboxxxxd
