### ISSUE TITLE
Future/Idea: A Interesting idea with Virtual Radio's!.

### ISSUE THREAD

**Issue by xboxxxxd** [mtadayz/MTADayZ#92]
I was Searching the web for like Hidden, Rare, MTA Resources..

And i found this resource added 2 years ago on github, it seems to fit in MTA:DayZ gamemode,
Maby edit it abit so it has the visual style of a Radio Communication Tool, or somthing like it.

Se what you can do, Check it out, it looks pretty nice i must say.
LINK: **https://github.com/AriosJentu/Lunix-OS-Phone** 

Greetings.xboxxxxd

**Comment by Blumlaut** [comment]
Wouldn't fit the DayZ resource at all imo, would be better if you added it on your server if you wanted.

**Comment by 0xCiBeR** [comment]
Well just to start off, a cell phone in a post apocalyptic scenario is just ridiculous. I'm not insulting tho your idea, but it just doesn't seem valid for MTA:DayZ at least for the moment. Thank's anyway for the suggestion.

**Comment by xboxxxxd** [comment]
Thats okey, it was just an idea :+1:
