### ISSUE TITLE
V0.9.8a hunger and thirst does not change

### ISSUE THREAD

**Issue by fastdelaspeed** [mtadayz/MTADayZ#94]
Just updated from v0.9.6a and I am loving the new features but how come hunger and thirst don't change at all? is this a bug or a feature of the "normal" difficulty?

**Comment by ghost** [comment]
Dear survivor,

Thank you to you for the report. No this is not an new feature, it a new bug. Know that the 0.9.8a version is pre-release, I advised not you use it to make a server.

Rémi

**Comment by fastdelaspeed** [comment]
Oh, I didn't know it was a pre-release. I'll be downgrading. Thanks for replying!

**Comment by 0xCiBeR** [comment]
I'm closing this.
