### ISSUE TITLE
Global chat in DX Chat not shows

### ISSUE THREAD

**Issue by ghost** [mtadayz/MTADayZ#98]
There is no error to paste, simplest no work on 0.9.8a

**Comment by TexPlayJR** [comment]
It does not work for me either.
Greetings Great Friend VenadHD.
If you find a solution let me know.

**Comment by 0xCiBeR** [comment]
I'll look in to it when i have the chance.

**Comment by 0xCiBeR** [comment]
Works perfect. Press T, then press arrow up, write your message and press enter. GlobalChat Addon is deprecated and will be removed.
