### ISSUE TITLE
Thinking of hosting a new website if team members want it..

### ISSUE THREAD

**Issue by Risusama** [mtadayz/MTADayZ#99]
Hello to the MTADayZ team!
I think the title says it all... I am thinking of buying a webhosting package for MTADayZ website & stable releases. And I mean only STABLE releases. Pre-Releases and other Non-stable considered builds would be downloadable from github, to reserve website bandwidth. Maybe some lightweight forum software could also be installed.

Here are the specs of the plan.

```
20 GB HDD Space
50 Email addresses
Unlimited email lists
Unlimited databases
250 GB/month bandwidth
5 Sub-domains
5 Addon-domains
```

The price would be: 5euro / month
I would pay it myself.
Of course, anyone (preferably from inside the team) who wants to help either pay the bill and/or just help administrate the website, is more than allowed to do so. I can give these people access to the Webspace management by creating a subaccount.

What do you think about this?
###### ################NOTE

THIS QUESTION IS MOSTLY FOR THE MTADAYZ TEAM MEMBERS.
I count as the team members only the ones who currently have been marked as contributors, they are listed below. If after this date, 1st of September, 2016, someone is marked as contributor, I do not count them as one of the "current contributors", because they were not marked as one when I wrote this. I hope you understand.
- L
- ciber96
- PicardRemi
- Bluethefurry
- 1B0Y
- Loki214
- Renkon
- DebexeL
- Neves768
- imCEASER
- KaSkA3eR
- venadHD
- nokizorgue
###### 

Thank you for reading.
- Christian "DebexeL" Sarre

**Comment by 0xCiBeR** [comment]
Hey sorry for the late response. We currently have infrastructure to host multiple websites and test servers. I love that you are intrested in helping but thinks here are not moving at all. We still own mta-dayz.org and we can host web and beta test builds, but only if community has intrest in continuing DayZ development. I'll mark this as feedback and wait for community feedback on this matter. Also note that only 2 persons have real decision making at the moment. Currently "L" is away so the final decision actually relies on me. 

Regards, CiBeR.

**Comment by 0xCiBeR** [comment]
Well no feedback was provided, i guess you lost interest. Closing this
